#include "../includes/ft_printf.h"

int	main(void)
{
	// printf("");            //                    -> ""
	// printf("\n%"); //
	// printf("\n");                              //-> "$\n"
	// printf("\ntest");                            //-> "test"
	// printf("\ntest\n");                          //-> "test$\n"
	// printf("\n1234");                            //-> "1234"
	// printf("\n%%");                              //-> "%"
	// printf("\n%5%");                             //-> "    %"
	// printf("\n%-5%");                            //-> "%    "
	// printf("\n%.0%");                            //-> "%"
  	// printf("\n%%", "test");                      //-> "%"
  	// printf("\n%   %", "test");                   //-> "%"
  	// printf("\n%x", 42);                          //-> "2a"
  	// printf("\n%X", 42);                          //-> "2A"
  	// printf("\n%x", 0);                           //-> "0"
  	// printf("\n%X", 0);                           //-> "0"
  	// printf("\n%x", -42);                         //-> "ffffffd6"
  	// printf("\n%X", -42);                         //-> "FFFFFFD6"
  	// printf("\n%x", 4294967296);                  //-> "0"
  	// printf("\n%X", 4294967296);                  //-> "0"
  	// printf("\n%10x", 42);                        //-> "        2a"
  	// printf("\n%-10x", 42);                       //-> "2a        "
  	// printf("\n%lx", 4294967296);                 //-> "100000000"
  	// printf("\n%llX", 4294967296);                //-> "100000000"
  	// printf("\n%hx", 4294967296);                 //-> "0"
  	// printf("\n%hhX", 4294967296);                //-> "0"
  	// printf("\n%llx", -9223372036854775807);       //-> "7fffffffffffffff"
  	// printf("\n%llx", 9223372036854775807);       //-> "7fffffffffffffff"
  	// printf("\n%010x", 542);                      //-> "000000021e"
  	// printf("\n%-15x", 542);                      //-> "21e            "
  	// printf("\n%2x", 542);                        //-> "21e"
  	// printf("\n%.2x", 5427);                      //-> "1533"
  	// printf("\n%5.2x", 5427);                     //-> " 1533"
  	// printf("\n%#x", 42);                         //-> "0x2a"
  	// printf("\n%#llx", 9223372036854775807);      //-> "0x7fffffffffffffff"
  	// printf("\n%#x", 0);                          //-> "0"
  	// printf("\n%#x", 42);                         //-> "0x2a"
  	// printf("\n%#X", 42);                         //-> "0X2A"
  	// printf("\n%#8x", 42);                        //-> "    0x2a"
  	// printf("\n%#08x", 42);                       //-> "0x00002a"
  	// printf("\n%#-08x", 42);                      //-> "0x2a    "
  	// printf("\n@moulitest: %#.x %#.0x", 0, 0);    //-> "@moulitest:  "
  	// printf("\n@moulitest: %.x %.0x", 0, 0);      //-> "@moulitest:  "
  	// printf("\n@moulitest: %5.x %5.0x", 0, 0);    //-> "@moulitest:            "
  	printf("\n%s", "abc");                       //-> "abc"
  	printf("\n%s", "this is a string");          //-> "this is a string"
  	printf("\n%s ", "this is a string");         //-> "this is a string "
  	printf("\n%s  ", "this is a string");        //-> "this is a string  "
  	printf("\nthis is a %s", "string");          //-> "this is a string"
  	printf("\n%s is a string", "this");          //-> "this is a string"
  	printf("\nLine Feed %s", "\n");              //-> "Line Feed $\n"
  	printf("\n%10s is a string", "this");        //-> "      this is a string"
  	printf("\n%.2s is a string", "this");        //-> "th is a string"
  	printf("\n%5.2s is a string", "this");       //-> "   th is a string"
  	printf("\n%10s is a string", "");            //-> "           is a string"
  	printf("\n%.2s is a string", "");            //-> " is a string"
  	printf("\n%5.2s is a string", "");           //-> "      is a string"
  	printf("\n%-10s is a string", "this");       //-> "this       is a string"
  	printf("\n%-.2s is a string", "this");       //-> "th is a string"
  	printf("\n%-5.2s is a string", "this");      //-> "th    is a string"
  	printf("\n%-10s is a string", "");           //-> "           is a string"
  	printf("\n%-.2s is a string", "");           //-> " is a string"
  	printf("\n%-5.2s is a string", "");          //-> "      is a string"
  	printf("\n%s %s", "this", "is");             //-> "this is"
  	printf("\n%s %s %s", "this", "is", "a");     //-> "this is a"
  	printf("\n%s %s %s %s", "this", "is", "a", "multi"); //-> "this is a multi"
  	printf("\n%s %s %s %s string. gg!", "this", "is", "a", "multi", "string"); //-> "this is a multi string. gg!"
  	printf("\n%s%s%s%s%s", "this", "is", "a", "multi", "string");// -> "thisisamultistring"
  	printf("\n@moulitest: %s", NULL);       //     -> "@moulitest: (null)"
  	printf("\n%.2c", NULL);                 //     -> "^@"
  	printf("%c", 42);                     //     -> "*"
  	printf("%5c", 42);                    //     -> "    *"
  	printf("%-5c", 42);                   //     -> "*    "
  	printf("@moulitest: %c", 0);          //     -> "@moulitest: ^@"
  	printf("%2c", 0);                     //     -> " ^@"
  	printf("null %c and text", 0);        //     -> "null ^@ and text"
  	printf("% c", 0);                     //     -> "^@"
	}
